### ISSUE TITLE
Sheilds do not block arrows with "No slow" module enabled

### ISSUE THREAD

**Issue by Paradigm0001** [ImpactDevelopment/ImpactIssues#1490] opened 2019-08-01 15:37 UTC
**Describe the bug**
Blocking with a shield while having the "No slow" module incurs the inability to block projectiles with a shield.

**To Reproduce**
1. Enable the "No slow" module
2. Begin blocking with a shield in off hand
3. Have an entity/player shoot an arrow at you
4. Shield fails to block projectile, causing damage to player.

**Expected behavior**
The player will not be slowed by the shield and retain the ability to block projectiles.

- Impact Version: 4.7.2 on Minecraft 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods:
AppleSkin-mc1.12-1.0.9
BetterFps-1.4.8
ClientTweaks_1.12.2-3.1.11
Clumps-3.1.2
FastFurnace-1.12.2-1.3.1
FastLeafDecay-v14
FastWorkbench-1.12.2-1.7.2
Hwyla-1.8.26-B41_1.12.2
##Impact-4.7.2-1.12.2
InventoryTweaks-1.63
JRFTL[1.12.2]-1.1
Jade-0.1.0
Login_Shield-1.12.2-3-g7c6e7ac
MouseTweaks-2.10-mc1.12.2
OreExcavation-1.4.140
ctwatercan-1.12.2-0.4.5
gravestone-1.10.1
harvestables-1.2.1
jei_1.12.2-4.15.0.268
stg-1.12.2-1.2.3
- Operating System: Void GNU/Linux
- Window manager: i3-gaps
- Kernel version: linux 4.19.61_1
- Java runtime: `openjdk-jre-8u202b00_1` for the java environment

</details>

**Comment by Paradigm0001** [comment] 2019-08-01 15:40
Update: Further testing shows that the shield does not block any types of damage (Melee, blaze projectiles) when using the "No slow" module

**Comment by DanCuber** [comment] 2019-08-02 23:00
I've had this issue but it only seems to occur when blocking with a sword in your main hand, axes for example work fine (I haven't tried this while moving tho)

**Comment by MightyKnight** [comment] 2020-05-28 17:35
Duplicate of #467

**Closed by MightyKnight** 2020-05-28 17:35 UTC
Labels: Bug
