### ISSUE TITLE
Item Saver should stop all actions (digging) if it cannot save the item.

### ISSUE THREAD

**Issue by GER-NaN** [ImpactDevelopment/ImpactIssues#2437] opened 2020-06-13 20:16 UTC
Add an option so Item Saver will cancel all actions if it cannot inventory the item. Sometimes my inventory is full and Item Saver drops the item onto the ground, effectively loosing the item when I am AFK digging.

Put the option under Item Saver and call it "Do Not Drop". And it will cancel all actions if the item cannot be saved into inventory and it will not drop it onto the ground.

**Comment by dominikaaaa** [comment] 2020-06-13 20:17
This is pretty much a duplicate of #2222.

**Comment by dominikaaaa** [comment] 2020-06-13 20:17
This is pretty much a duplicate of #2222

**Closed by dominikaaaa** 2020-06-13 20:17 UTC
Labels: Duplicate
