### ISSUE TITLE
Mobspawn ESP [Suggestion]

### ISSUE THREAD

**Issue by kcarew98** [ImpactDevelopment/ImpactIssues#1816] opened 2019-11-02 18:19 UTC
Wurst has this, and is honestly very underrated for survival builders.

This feature would mark out on top of blocks whether or not a hostile mob can spawn on it. Mainly focusing on zombie/creeper/skeleton/spider spawning in the overworld.

- Marking with a red X indicates that mobs can spawn on top of this block (light level below threshold)
- Marking with a yellow X indicates that a mob can only spawn on top of this block during night time, so during the day, it is bright enough to prevent mob spawning, but becomes too dark at night.
- Blocks that are sufficiently lit have no marking, as mobs cannot spawn there.

This feature should also check if the block is solid or not, for example, spawning on top slabs is possible, but not on bottom slabs or glass etc.

Would love to see this added. Will donate for early access if this is added for 1.15 update

**Comment by S-B99** [comment] 2020-03-08 16:16
Duplicate of #1597

**Closed by S-B99** 2020-03-08 16:16 UTC
