### ISSUE TITLE
Auto Obby

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactIssues#1463] opened 2019-07-27 05:13 UTC
Auto places obsidian around your legs to prevent endcrystals from damaging you
Should do constant checks to replace obby or just replace a broken obsidian immediately

**Comment by StijnSimons** [comment] 2019-07-27 09:24
A crystal explodes within a tick... You can't place many blocks in one tick.

**Comment by Infernopickaxe** [comment] 2019-07-27 14:19
I have seen auto obbys react faster than auto crystals can

**Comment by MightyKnight** [comment] 2020-03-24 16:22
Resolving your issue as a duplicate, even though it's the oldest. Other issue has more information.
Duplicate of #1922

**Closed by MightyKnight** 2020-03-24 16:22 UTC
Labels: Suggestion
