### ISSUE TITLE
Auto place torches

### ISSUE THREAD

**Issue by bentenjamin** [ImpactDevelopment/ImpactIssues#1898] opened 2019-12-09 13:32 UTC
I really dislike having to switch to torches every 5 blocks to place a torch while mining or exploring. While i understand "just use kill aura" i prefer caves and my base to be lit up.

Torches would be automatically placed on blocks that can spawn mobs on (below light level) using torches from the hotbar.

Some placing ideas would be placing on blocks that are spawnable or placing in the 'optimal' spot to light as many blocks as possible without missing any between the previous torch.
Refilling hotbar slot from inventory.

I use the Lantern Of Paranoia from Xenos Reliquery in mod packs religiously and this is where i got the idea.

**Comment by SpicyBigDaddy-alt** [comment] 2019-12-09 21:42
Fullbright

**Comment by SentinelMKX** [comment] 2019-12-09 21:43
Light module doesn't prevent mobs to spawn.

**Comment by S-B99** [comment] 2020-03-08 16:18
Duplicate of #1125

**Closed by S-B99** 2020-03-08 16:18 UTC
Labels: Suggestion
