### ISSUE TITLE
Mob spawn overlay

### ISSUE THREAD

**Issue by Triggerhacks** [ImpactDevelopment/ImpactIssues#1946] opened 2020-01-16 12:54 UTC
**Is your feature request related to a problem? Please describe.**
The light option allows increasing of gamma, but that makes it difficult to recognise where mobs can spawn.

**Describe the solution you'd like**
An option that allows an overlay that shows where mobs can spawn on blocks depending on light level and day/night.

**Describe alternatives you've considered**
I think Optifine supports this, but as it increases the chance of crashing the game I'd rather not use it

**Comment by aUniqueUser** [comment] 2020-01-16 13:50
You can use F3 to view the light level, or just temporarily turn off light.

**Comment by Mcknife96** [comment] 2020-03-08 13:23
Nah that really is a useful module to have your base completely lit up.
WWE has it and it is a bit laggy but works.

**Comment by S-B99** [comment] 2020-03-08 16:15
Duplicate of #1597

**Closed by S-B99** 2020-03-08 16:15 UTC
Labels: Suggestion
