### ISSUE TITLE
Crystal Aura Placement overrides actions

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactIssues#1496] opened 2019-08-02 23:18 UTC
Whenever Crystal Aura Placement is enabled, and there's a target in range, the placement will override and take precedence over any action the player is doing.

What it should do instead is wait for the current action to be over and then place (I.e. it will wait for you to finish eating a gapple before placing the crystal)

**Comment by MightyKnight** [comment] 2020-05-30 12:21
Duplicate of #1256

**Closed by MightyKnight** 2020-05-30 12:21 UTC
Labels: Bug
