### ISSUE TITLE
Baritone active after self destructing client

### ISSUE THREAD

**Issue by Lukasvd123** [ImpactDevelopment/ImpactIssues#2362] opened 2020-06-05 08:38 UTC
**Describe the bug**
Baritone keeps working after I self destruct the whole client 

**To Reproduce**
1. Self destruct
2. Do #help
3. See error

**Expected behavior**
That baritone would also shut down

**Screenshots**
-

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by MightyKnight** [comment] 2020-06-08 01:26
This is a duplicate of #849, meaning it is already reported. Further information belongs there.

**Closed by MightyKnight** 2020-06-08 01:26 UTC
Labels: Bug
