### ISSUE TITLE
Minecraft crashes when trying to change friend alias.

### ISSUE THREAD

**Issue by HowAboutIf** [ImpactDevelopment/ImpactIssues#2351] opened 2020-05-31 11:48 UTC
**Describe the bug**
When trying to add or remove an alias from a friend Impact causes Minecraft to crash, regardless if it's on the title screen or in-game.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Impact settings'
2. Click on 'Friends'
3. Select a friend and click 'Edit'.
4. Change alias.
5. See error

**Expected behaviour**
To simply change the alias without crashing.

**Screenshots**
https://imgur.com/a/Dm0IfWH

<details> 
  <summary><strong>Game output</strong></summary>
 

```
12:43:48.859
Preparing to launch minecraft client for 1.12.2-Impact_4.8.3
12:43:49.382
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
12:43:49.385
Have local file C:\Users\kskor\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
12:43:49.387
Checking installations.
12:43:49.388
Minecraft client 1.12.2-Impact_4.8.3 is ready to start.
12:43:49.388
Starting!
12:43:49.908
Using default game log configuration client-1.12.xml (outputs XML)
12:43:50.757
Loading tweak class name clientapi.load.ClientTweaker
12:43:50.764
Using primary tweak class name clientapi.load.ClientTweaker
12:43:50.765
Loading tweak class name baritone.launch.BaritoneTweaker
12:43:50.766
Calling tweak class clientapi.load.ClientTweaker
12:43:50.771
Injecting into ClassLoader
12:43:50.908
SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/kskor/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
12:43:51.317
FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/31/20 12:42 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.impactclient.3i.a(3i.java:51)
	at blk.redirect$actionPerformed$zeb000(SourceFile:571)
	at blk.a(SourceFile:337)
	at net.impactclient.3i.a(3i.java:11)
	at blk.k(SourceFile:400)
	at blk.q(SourceFile:377)
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.3i.a(3i.java:51)
	at blk.redirect$actionPerformed$zeb000(SourceFile:571)
	at blk.a(SourceFile:337)
	at net.impactclient.3i.a(3i.java:11)
	at blk.k(SourceFile:400)
	at blk.q(SourceFile:377)

-- Affected screen --
Details:
	Screen name: net.impactclient.3i
Stacktrace:
	at bib.t(SourceFile:1625)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 409363760 bytes (390 MB) / 671088640 bytes (640 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.8.3
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.3 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: Windows 10 64bit

</details>

**Additional context**
N/A

**Comment by MightyKnight** [comment] 2020-06-03 11:26
Duplicate of #1973 
If you would like to add a vote or extra information to the other issue it would be appreciated.

**Closed by MightyKnight** 2020-06-03 11:26 UTC
Labels: Bug
