### ISSUE TITLE
F3+A update when i just press the a key

### ISSUE THREAD

**Issue by Hameij** [ImpactDevelopment/ImpactIssues#699] opened 2018-08-20 17:45 UTC
When i press the key A to walk left the world updates like when you press F3+A

When I start minecraft with Impact 4.3 client and join a server and press just the a key to walk left the world updates just like when you press F3+A

### What happens?
The world updates just like F3+A When i press just the A key on my keyboard.

### Exact steps to reproduce?

- Start Minecraft with Impact 4.3 Client
- Join a server
- Press the A key on keyboard

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.3 for 1.12.2
- Using Optifine? 
- Enabled mods:
- Operating System: 

</details>

**Comment by VitorISs** [comment] 2018-08-20 17:49
uh.. are you sure this isn't a problem with your keyboard or something else related to your keys?

**Comment by Hameij** [comment] 2018-08-20 17:51
Naw man i tried this with the 4.1 and the 4.2 and only the 4.1 client did not have any problems

**Comment by WaffleTraits** [comment] 2018-08-20 17:58
Attempted to reproduce according to provided steps, could not reproduce.

**Comment by Hameij** [comment] 2018-08-20 20:38
Maybe just a bug for me then huh

**Comment by LeafHacker** [comment] 2018-08-20 20:54
If this only affects 4.1 and not 4.2+ then this is already fixed... in 4.2

Also, is #698 a duplicate of this?

**Comment by MightyKnight** [comment] 2018-08-20 21:57
You may have misread his comment. It says that the bug started occuring in 4.2 (and didn't in 4.1). Also in steps to reproduce and description he wrote 4.3.

@Hameij Please tell us in which versions exactly this issue occurs.

**Comment by Hameij** [comment] 2018-08-21 15:31
The issue only happens in impact client 4.2+

**Comment by dominikaaaa** [comment] 2020-09-22 00:21
Closed as stale. Reopen if you can still reproduce this.

**Closed by dominikaaaa** 2020-09-22 00:21 UTC
Labels: Awaiting response
