### ISSUE TITLE
Autoweapon return tool

### ISSUE THREAD

**Issue by ChiefAwesome301** [ImpactDevelopment/ImpactIssues#2100] opened 2020-03-28 01:17 UTC
**Is your feature request related to a problem? Please describe.**
So I want to be able to have autoweapon return to the last item. When I am AFK fish farming, I have killaura on so I dont get killed. I come back and my sword is out.

**Describe the solution you'd like**
It would be nice to have a setting to return to the item before it used the autoweapon.

**Comment by S-B99** [comment] 2020-03-28 13:42
Duplicate of #1033

**Closed by S-B99** 2020-03-28 13:42 UTC
Labels: Suggestion
