### ISSUE TITLE
"Wireframes" were turned on yet nothing changes.

### ISSUE THREAD

**Issue by BlackHanbo** [ImpactDevelopment/ImpactIssues#2037] opened 2020-03-03 14:04 UTC
**Describe the bug**
Although "Wireframes" were turned on, nothing changes

**To Reproduce**
just turning it on

**Expected behavior**
only see the outline of blocks

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by S-B99** [comment] 2020-03-04 13:15
Duplicate of #2034

**Closed** 2020-03-04 13:15 UTC
Labels: Bug
