### ISSUE TITLE
Freecam doesn't disable auto walk

### ISSUE THREAD

**Issue by RqndomHax** [ImpactDevelopment/ImpactIssues#1864] opened 2019-11-23 10:53 UTC
**Describe the bug**
When freecam is on, my player is moving around for no reason...

**To Reproduce**
Just turn on freecam
But I don't know why it happens

**Video**
Here is a video of the bug -> https://streamable.com/9guad

<details> 
  <summary><strong>Game output</strong></summary>
 

```
1920x1080
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods:  Chams (Wallhack), Auto Weapon, Anti Overlay, Radar (Static), Storage (ESP), ESP (shader), Animations, Anti Vanish, Crosshair+, Anti Blind, Auto Fish, Inventory, Auto Eat, Tracers, Sprint, Light    
- Operating System:  Windows 10 64bit

</details>

**Additional context**
No additional context :)

**Comment by lilZoeyXanax** [comment] 2020-01-29 01:17
This bug is caused by opening freecam while auto walk is on. this results in (even when auto walk is off) for freecam to think you should be walking. The only fix I know of is relaunching your client.

Ex: long nether tunnel, so you turn on auto walk, you want to look around while auto walking so you enable freecam. even when you turn freecam off, and turn auto walk off, the next time you enable freecam (until you relaunch the client again) will result in it thinking autowalk is still enabled.

**Comment by S-B99** [comment] 2020-01-29 01:18
Wasn't this fixed with https://github.com/ImpactDevelopment/ImpactIssues/issues/679

**Comment by LeafHacker** [comment] 2020-01-29 01:48
That was antiafk, this is freecam, but otherwise the symptoms are similar

**Comment by leijurv** [comment] 2020-02-06 01:49
Duplicate of #1679

**Closed by leijurv** 2020-02-06 01:49 UTC
Labels: Bug
