### ISSUE TITLE
[1.14] Alternative accounts not available.

### ISSUE THREAD

**Issue by Fryke** [ImpactDevelopment/ImpactIssues#1581] opened 2019-08-20 21:33 UTC
**Describe the bug**
After adding an alternative account and opening the 'alts' page, the client crashes.

**To Reproduce**
1. Install build 4.8.0-20190817-nightly
2. After installing and launching to the main menu
3. Add a new premium account to the alt list.
4. Re-launch the client.
5. Try going to the 'alts' tab on the main menu.
6. Client crashes.

**Expected behavior**
Able to click on the 'alts' tab and get to the next menu. 

**Screenshots**
[![Screenshot-19.png](https://i.postimg.cc/fLwkXRWB/Screenshot-19.png)](https://postimg.cc/sBNVCyhh)
After clicking on the 'alts' tab the clients shows a breef moment of 'Saving world'

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// My bad.

Time: 8/20/19 11:11 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at dsz.a(SourceFile:488)
	at dsz.b(SourceFile:451)
	at dsz.a(SourceFile:28)
	at dsb.a(SourceFile:64)
	at dsz.a(SourceFile:179)
	at dwn.a(SourceFile:67)
	at dwn.a(SourceFile:34)
	at dsa.a(SourceFile:385)
	at net.impactclient.5h.render(Unknown Source)
	at dnc.a(SourceFile:686)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dsz.a(SourceFile:488)
	at dsz.b(SourceFile:451)
	at dsz.a(SourceFile:28)
	at dsb.a(SourceFile:64)
	at dsz.a(SourceFile:179)
	at dwn.a(SourceFile:67)
	at dwn.a(SourceFile:34)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.impactclient.85)
	Entity ID: 72
	Entity Name: e-mail
	Entity's Exact location: 8.50, 65.00, 8.50
	Entity's Block location: World: (8,65,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: dwn@129f4465
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.1
Stacktrace:
	at dsa.a(SourceFile:385)
	at net.impactclient.5h.render(Unknown Source)

-- Screen render details --
Details:
	Screen name: net.impactclient.5h
	Mouse location: Scaled: (243, 298). Absolute: (487.000000, 596.000000)
	Screen size: Scaled: (479, 504). Absolute: (958, 1008). Scale factor of 2.000000
Stacktrace:
	at dnc.a(SourceFile:686)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 927457608 bytes (884 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Impact_4.8.0-20190817-nightly
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 5.00GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.0-20190817-nightly 
- Using Optifine: No
- Enabled mods: Auto Reconnect, Auto Weapon, Anti Overlay, Log Position, New Chunks, Storage ESP, Anti Hazard, Trajectories, Anti Desync, Auto Totem, Bow Aimbot, Anti Vanish, Auto Cheat, Item Saver, Auto Eject, Nametags, Auto Tool, Anti Blind, Inventory, Auto Eat, Respawn, Weather, Unpack, Tracers, No SRP, Portals, HitBox, Radar, Light, ESP.
- Operating System: Windows 10 Pro 64-Bit

</details>

**Additional context**
Problem also occurs on 4.8.0-20190818-nightly & 4.8.0-20190819-nightly

**Comment by leijurv** [comment] 2019-08-20 21:40
Already fixed for today's nightly, probable duplicate of #1562. Reopen if not fixed in 20190820.

**Closed by leijurv** 2019-08-20 21:40 UTC
Labels: 1.14, Bug
