### ISSUE TITLE
No blocks working through X-Ray

### ISSUE THREAD

**Issue by Strikerrr** [ImpactDevelopment/ImpactIssues#1838] opened 2019-11-08 18:58 UTC
**Describe the bug**
When I'm trying to use Xray, no blocks are disappearing at all. The screen only goes a bit brighter. 

**To Reproduce**
I don't know how this happened

**Expected behavior**

**Screenshots**
https://i.imgur.com/ftmpHPL.png

<details> 
  <summary><strong>Game output</strong></summary>
</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.8.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Xray
- Operating System: Windows 10 64bit

</details>

**Additional context**
This happened when I tried using Xray in the nether. Ever since I came back it stopped. Tried a complete reinstall of Impact, didnt work.

**Comment by SentinelMKX** [comment] 2019-11-08 19:02
Optifine breaks Xray, so for now install a version of Impact without Optifine if you want to use Xray from Impact.

**Comment by Strikerrr** [comment] 2019-11-08 19:03
> Optifine breaks Xray, so for now install a version of Impact without Optifine if you want to use Xray from Impact.

That's interesting. It was working yesterday for me, with Optifine.

**Comment by Dad3** [comment] 2019-11-08 20:17
> Optifine breaks Xray, so for now install a version of Impact without Optifine if you want to use Xray from Impact.

will this be fixed or is it a permanent bug

**Comment by SentinelMKX** [comment] 2019-11-08 20:18
Developers would like to fix it but they don't know where the problem is, as one of them said.

**Comment by Dad3** [comment] 2019-11-08 20:28
Also why does wireframe work and not xray, dont they use the same mechanism?

**Comment by SentinelMKX** [comment] 2019-11-08 20:29
I don't think they do, wireframe is using some different method of rendering or something.

**Comment by S-B99** [comment] 2020-02-26 13:50
This should be fixed in latest.

**Closed by S-B99** 2020-02-26 13:50 UTC
Labels: Bug
