### ISSUE TITLE
TriggerBot Enhancement

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactIssues#470] opened 2017-11-16 21:56 UTC
You should add a setting in trigger bot that allows the trigger bot to automatically attack when you are looking at an entity, and should have it configurable between players, mobs, and monsters. I dont really like how you cant break anything when having it on, and this would actually work a lot better than killaura to some players.

**Comment by 6BytesIn** [comment] 2017-11-16 22:38
Yes, what he said.

**Comment by GlitchHead** [comment] 2017-11-16 23:00
Duplicate of #465 its already coming in 4.20

**Comment by GlitchHead** [comment] 2017-11-17 11:50
But you are right. We should be able to break blocks with it on. If it had Kilauea settings it would definitely be easier to make the mod look legit

**Comment by InstantReflex** [comment] 2017-12-02 20:27
> Duplicate of #465 its already coming in 4.20

Its not a duplicate. Your idea was to HOLD the left click. My idea was to have it be similar to killaura in the sense of automation. I requested that it automatically hit the entity when it is on the crosshair. This can kinda be done in killaura to an extent, but it would be MUCH more reliable if it had a dedicated hack.

**Comment by ZeroMemes** [comment] 2020-03-29 23:46
This is available as an extension to the `Auto Clicker` module.

**Closed by ZeroMemes** 2020-03-29 23:46 UTC
Labels: Suggestion
