### ISSUE TITLE
murder not working!

### ISSUE THREAD

**Issue by TheKingErnest** [ImpactDevelopment/ImpactIssues#2088] opened 2020-03-24 21:07 UTC
I'm sorry for my English but my native language is another
Hypixel murder is not detecting murder when he uses a different sword than normal for example feather

1. Play Hypixel
2. Find a session where murder have feather except of sword
3. See, the murderer is not red coloured

Impact will detect murder always

- Impact Version: nightly-20200319 for 1.15.2 this bug is  also on another versions I checked it(4.8 for 1.12.2, 4.8 for 1.14.4, nightly-20200323 for 1.12.2)
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: only Murder
- Operating System: Windows 10 64bit

**Comment by S-B99** [comment] 2020-03-24 22:38
Duplicate of #1894

**Closed by S-B99** 2020-03-24 22:38 UTC
Labels: Bug
