### ISSUE TITLE
Killaura dragon attack crash

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2123] opened 2020-03-31 15:00 UTC
**Describe the bug**
Killaura attacking ender dragon crashes the game

**To Reproduce**
1. Enable killaura
2. Try to attack dragon

**Expected behavior**
Not crashing

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 31/03/20 4:58 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.impactclient.84.2(84.java:215)
	at net.impactclient.84$$Lambda$2098/743502251.test(Unknown Source)
	at net.impactclient.0Gy.0(0Gy.java:2)
	at net.impactclient.5B.0(5B.java:20)
	at net.impactclient.5B$$Lambda$3192/123356622.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.impactclient.5B.0(5B.java:5)
	at net.impactclient.00$$Lambda$3336/1572600325.test(Unknown Source)
	at net.impactclient.00.0(00.java:77)
	at net.impactclient.00$$Lambda$3337/855692223.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.00.0(00.java:4)
	at net.impactclient.0m6.0(0m6.java:2)
	at net.impactclient.0mp.0(0mp.java:9)
	at net.impactclient.84.0(84.java:222)
	at net.impactclient.84$$Lambda$2070/257876184.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1988/1387460501.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.5L.post(5L.java:3)
	at dqb.handler$onPreUpdateWalking$zzd000(SourceFile:1257)
	at dqb.eE(SourceFile)
	at dqb.h(SourceFile:214)
	at dno.a(ClientWorld.java:235)
	at dno$$Lambda$3154/935620966.accept(Unknown Source)
	at bjw.a(SourceFile:534)
	at dno.g(ClientWorld.java:196)
	at dbn.p(SourceFile:1467)
	at dbn.d(SourceFile:964)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.impactclient.84.2(84.java:215)
	at net.impactclient.84$$Lambda$2098/743502251.test(Unknown Source)
	at net.impactclient.0Gy.0(0Gy.java:2)
	at net.impactclient.5B.0(5B.java:20)
	at net.impactclient.5B$$Lambda$3192/123356622.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.impactclient.5B.0(5B.java:5)
	at net.impactclient.00$$Lambda$3336/1572600325.test(Unknown Source)
	at net.impactclient.00.0(00.java:77)
	at net.impactclient.00$$Lambda$3337/855692223.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.impactclient.00.0(00.java:4)
	at net.impactclient.0m6.0(0m6.java:2)
	at net.impactclient.0mp.0(0mp.java:9)
	at net.impactclient.84.0(84.java:222)
	at net.impactclient.84$$Lambda$2070/257876184.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1988/1387460501.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at net.impactclient.5L.post(5L.java:3)
	at dqb.handler$onPreUpdateWalking$zzd000(SourceFile:1257)
	at dqb.eE(SourceFile)
	at dqb.h(SourceFile:214)
	at dno.a(ClientWorld.java:235)
	at dno$$Lambda$3154/935620966.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (dqb)
	Entity ID: 147492
	Entity Name: ThaUnknown_
	Entity's Exact location: -32.96, 98.48, 13.66
	Entity's Block location: World: (-33,98,13), Chunk: (at 15,6,13 in -3,0; contains blocks -48,0,0 to -33,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -1.30, 0.68, 3.27
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at bjw.a(SourceFile:534)
	at dno.g(ClientWorld.java:196)

-- Affected level --
Details:
	All players: 1 total; [dqb['ThaUnknown_'/147492, l='MpServer', x=-32.96, y=98.48, z=13.66]]
	Chunk stats: Client Chunk Cache: 1521, 1155
	Level dimension: minecraft:the_end
	Level name: MpServer
	Level seed: -9007869012688078752
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,66,80), Chunk: (at 0,4,0 in -14,5; contains blocks -224,0,80 to -209,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9927344 game time, 4889089 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:634)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4991320624 bytes (4760 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 14 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	Launched Version: 1.15.2-Impact_nightly-20200328-OptiFine_HD_U_G1_pre10
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.50, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r249461.zip (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 24
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.50
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: nightly 20200328 for 1.15.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Killaura
- Operating System: Win1064

</details>

**Comment by MightyKnight** [comment] 2020-03-31 16:09
Duplicate of #2079

**Closed by MightyKnight** 2020-03-31 16:09 UTC
Labels: Bug
