### ISSUE TITLE
ESP entity colours

### ISSUE THREAD

**Issue by TobSick** [ImpactDevelopment/ImpactIssues#2065] opened 2020-03-16 00:38 UTC
**Behaviour**
Option for different entities to be different colours. Under each entity, friends, teammates. Have an option for colour, which can be custom or health.

**Example because I can't explain**
Option for player's ESP to be health, hostile mobs to be, say, red, and friends to be blue, etc...

**Extension**
Would it also be possible to have the Health colour be customisable, so that blue could be max health, and purple could be low health?

**Comment by S-B99** [comment] 2020-03-16 00:41
Duplicate of #1940

**Closed by S-B99** 2020-03-16 00:41 UTC
Labels: Suggestion
