### ISSUE TITLE
scaffold opening workbenches

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactIssues#1311] opened 2019-06-20 21:32 UTC
**Describe the bug**
scaffold is opening workbenches instead of placing blocks on them

**To Reproduce**
1. enable scaffold
2. try to go over workbench

**Expected behavior**
scaffold should place blocks

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: latest for minecraft 1.12.2
- Using Optifine? yes
- Using LiteLoader? no
- Enabled mods: 
- Operating System: win10 PRro x64 1903

</details>

**Additional context**
[video](https://streamable.com/5uyuy)
[mods that I had on](https://i.imgur.com/48p8AoM.jpg)

**Comment by Cerbiac** [comment] 2019-06-20 22:10
Similar effect with builder.

**Comment by leijurv** [comment] 2019-06-21 04:33
`BuilderProcess` would never do this

**Comment by ZeroMemes** [comment] 2019-06-21 05:01
This is a sneak and unsneak moment if you can't place on any other blocks moment.

**Comment by a6d6061ed1** [comment] 2019-06-24 22:29
I also noticed another scaffold problem that's probably strongly related to this. Scaffold will attempt to place blocks in spaces where it's not possible causing player's view to "warp". For instance when you jump over "air block" that has a torch placed on the side of one of its contiguous blocks

**Comment by dominikaaaa** [comment] 2020-09-22 00:45
This should be fixed, can't reproduce.

**Closed by dominikaaaa** 2020-09-22 00:45 UTC
Labels: Bug
