### ISSUE TITLE
2b2t queue module

### ISSUE THREAD

**Issue by TNTDoctor** [ImpactDevelopment/ImpactIssues#2872] opened 2021-01-28 17:53 UTC
I think that there could be a 2b2t queue module where when the queue reaches a cerrtain position it makes loud sounds so that you can afk while in the queue.

**Comment by berrely** [comment] 2021-01-30 11:09
Duplicate of  #1966. Queue plays a sound anyways at postion 1-5.

**Closed by berrely** 2021-01-30 11:09 UTC
Labels: Suggestion
