### ISSUE TITLE
Game Crashes when i try to open a link

### ISSUE THREAD

**Issue by ItsAlvinThePro** [ImpactDevelopment/ImpactIssues#2251] opened 2020-05-06 07:48 UTC
**Describe the bug**
I have noticed 1 problem while using this client. Everytime i click a link it crashes! I hope you fix this problem in the future!

**To Reproduce**
1. Link pops up in chat.
2. I click on the link.
3. I confirm that i want to open link
4. CRASH

**Expected behavior**
I expected that the link would open...

**Screenshots**
https://gyazo.com/7cfe86e05f44c8adabc81c9dd8206409
https://gyazo.com/4be6ba6301e9db45042e35fc1be661a7
https://gyazo.com/e4bc2b91158b0da1230b18c1c2d5b27c

<details> 
  <summary><strong>Game output</strong></summary>
 

```
https://pastebin.com/3iWYJqAf
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://pastebin.com/vg4FF2qH
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8 for 1.14.4
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Nothing
- Operating System: Windows 10 64bit

</details>

**Additional context**

**Comment by ScanmanTM** [comment] 2020-05-11 14:08
Duplicate of #1768

**Closed by ScanmanTM** 2020-05-11 14:08 UTC
Labels: Bug
