### ISSUE TITLE
Bed Aura (same as crystal aura)

### ISSUE THREAD

**Issue by Yertled** [ImpactDevelopment/ImpactIssues#1751] opened 2019-10-14 10:40 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Bed Aura would place a bed next to a enemy then right click it instantly so it explodes. (for nether and end dimensions)
Would be same as Crystal Aura, but instead of placing crystals and punching them, it would be a bed and right click them.

**Describe alternatives you've considered**
Another option under Crystal Aura?

**Additional context**
Also add safety features to not kill yourself using it and such.

**Comment by LeafHacker** [comment] 2019-10-14 17:13
IMO this and the existing crystal aura should both be options under a new “Bomber” module

**Comment by usereewrjrjeejr** [comment] 2019-10-23 13:06
No one uses beds in the meta anyway q

**Comment by Kami147** [comment] 2019-10-25 11:22
> No one uses beds in the meta anyway

Yeah but most newf*gs can't get they hands on crystals so this is good for they lot

**Comment by Quazar5** [comment] 2019-11-19 02:35
LeafHacker I'd love more CrystalAura options!  A new module dedicated to it would be amazing.

**Comment by dominikaaaa** [comment] 2020-05-03 18:04
Duplicate of #216

**Closed by dominikaaaa** 2020-05-03 18:04 UTC
Labels: Suggestion
