### ISSUE TITLE
Portal Tracers

### ISSUE THREAD

**Issue by Raulsack** [ImpactDevelopment/ImpactIssues#1638] opened 2019-09-10 22:49 UTC
**Is your feature request related to a problem? Please describe.**
Not related to any specific issues.

**Describe the solution you'd like**
A single tracer drawn to the center of a portal with it's own tracer color/thickness options completely separate from search. This way you don't have a ton of tracers show up for large portals and can distinguish them easily from other things you are searching for.

**Describe alternatives you've considered**
Just using search and dealing with dozens of potential tracers to each individual portal block and not being able to distinguish portals from other things in my search list.

**Additional context**
None.

**Comment by ephility** [comment] 2019-09-10 23:33
just use search smh

**Comment by Raulsack** [comment] 2019-09-11 01:34
But having hundreds of tracers in portal-dense areas and massive portals not only looks terrible but also can even kill the FPS. You should only really need one tracer per portal no matter the size.

**Comment by 0xx06** [comment] 2019-09-11 09:34
@ephility are you trying to be as little helpful as possible, he has a valid suggestion. I myself thought of this too.

**Comment by ephility** [comment] 2019-09-11 23:25
that’s all the help I can give, moron
simply just yknow **use search** 
yes it tanks fps, for a minute or two.

**Comment by 0xx06** [comment] 2019-09-12 07:11
you're not helping anyone since all you say is "use search" which op actually included in his post as alternatives he considered. 
if you are fine with cluttered search tracers for big portals or areas with many portals making it impossible to distinguish other blocks in the search list then fine, you  do you. however op has a valid reason to voice his concern, as he wrote in his post, so why come here and be as unhelpful and rude as possible?

**Comment by MightyKnight** [comment] 2020-03-19 18:07
Duplicate of #1208.
Please move discussion to there.

**Closed by MightyKnight** 2020-03-19 18:07 UTC
Labels: Suggestion
