### ISSUE TITLE
Some kind of waypoint beacon to know what direction to go for far away points

### ISSUE THREAD

**Issue by HexCodeFFF** [ImpactDevelopment/ImpactIssues#2138] opened 2020-04-03 22:47 UTC
**Is your feature request related to a problem? Please describe.**
I've been hunting woodland mansions and flying there with my elytra but im not sure exactly where to look to go to the mansion since its like 20k blocks away usually

**Describe the solution you'd like**
Some kind of beacon-like waypoint thing to vaguely point you in the right direction. Similar to the way baritone GoalXZ is rendered but viewable from infinitely far away

**Describe alternatives you've considered**
ive just like looked at the coordinates

**Additional context**
j

**Comment by MightyKnight** [comment] 2020-04-04 01:17
Duplicate of #1112

**Closed by MightyKnight** 2020-04-04 01:17 UTC
Labels: Suggestion
