### ISSUE TITLE
My Game Crashes When I Turn On Almost Anying Under The "HUD" Module On 1.12.2

### ISSUE THREAD

**Issue by MichelTGM** [ImpactDevelopment/ImpactIssues#2754] opened 2020-12-09 21:02 UTC
**Describe the bug**
My game will crash when i i turn on anything under "hud"

**To Reproduce**
1. Go to 'ClickGUI'
2. Click on 'HUD'
3. Scroll down to 'Any setting'

**Expected behavior**
The Game Should Not Chrash

**Screenshots**
I'm Sorry, I can not give screenshots for this

 

 

- Impact Version: <4.9.1 on 1.12.2>
- Using Optifine? <Yes (but it also does this without optifine>
- Using LiteLoader? <no>
- Enabled mods: <just HUD>
- Operating System: <Windows 10 64bit>

</details>

**Additional context**
I do Have The Game Log I Will Post It, also latest version of java (this log is from a couple of days ago when i was going to post this but didn't have the time, but nothing has changed since then)
[hs_err_pid35460.log](https://github.com/ImpactDevelopment/ImpactIssues/files/5668643/hs_err_pid35460.log)

**Comment by l1ving** [comment] 2020-12-09 21:58
post your gpu model and driver version

**Comment by MichelTGM** [comment] 2020-12-09 23:17
GPU: Intel HD Graphics 4000 VER: 1..18.10.4358 (BTW HUD worked like a month ago)

**Comment by l1ving** [comment] 2020-12-10 00:59
That's like a 9 year old CPU, it probably won't be fixed. Best thing you can try is updating drivers but I doubt it, the crash is caused by your gpu not supporting the more modern features of GL which Impact is using now

**Closed** 2020-12-10 00:59 UTC
Labels: Awaiting response, Bug, Won't fix

**Comment by MichelTGM** [comment] 2020-12-10 01:03
Okay Thanks for the help!
