### ISSUE TITLE
[SUGGESTION]No Steal Button in shulker boxes.

### ISSUE THREAD

**Issue by cancerousname69** [ImpactDevelopment/ImpactIssues#1362] opened 2019-07-16 18:31 UTC
Should be easy to add for the respective versions

**Comment by zPeanut** [comment] 2019-07-20 15:14
this is more of a suggestion than a bug

**Comment by mrphax0r** [comment] 2019-07-20 17:10
:/

**Comment by MightyKnight** [comment] 2020-03-29 01:14
Duplicate of #877

**Closed by MightyKnight** 2020-03-29 01:14 UTC
Labels: Suggestion
