### ISSUE TITLE
Auto Mount feature

### ISSUE THREAD

**Issue by CammB** [ImpactDevelopment/ImpactIssues#2277] opened 2020-05-13 11:31 UTC
**Describe the solution you'd like**
An auto mount entity feature similar to future client that would assist in bypassing duping patch plugins.

**Comment by ScanmanTM** [comment] 2020-05-13 13:43
Dupe of #1778, next time search for existing issues SalC1 fanboy.

**Closed by ScanmanTM** 2020-05-13 13:43 UTC
Labels: Suggestion

**Comment by dominikaaaa** [comment] 2020-05-13 20:20
Actually it's different. They're asking you to add a module which executes one line of code, which cancels mount packets.

**Comment by ScanmanTM** [comment] 2020-05-14 07:09
You can reopen if you want.

**Comment by dominikaaaa** [comment] 2020-05-14 18:49
The mount bypass relies on a shitty anti dupe plugin which some anarchy servers use. No doubt it'll be fixed within a week anyways
