### ISSUE TITLE
New parkour module

### ISSUE THREAD

**Issue by Simann** [ImpactDevelopment/ImpactIssues#2049] opened 2020-03-07 18:18 UTC
A module mainly used for parkour:
You enable it and it works like blink:
(movement packets are not send to server)
You jump and if you fall more than [number] blocks the packets get destroyed and you can try the jump again untill you succeed. If you successfully make the jump the packets are send as they would be normally (to not get kicked for sending too many packets)
Options:
-Number of blocks to fall to not send the packets
-Auto send packets if you touch block after jumping
-Pick a block to land on if not successful then don't send the packets

**Comment by S-B99** [comment] 2020-03-07 18:19
What's your question?

**Comment by Simann** [comment] 2020-03-07 18:23
Hey I accidentally set a wrong label sorry

**Comment by S-B99** [comment] 2020-03-07 18:23
bruh moment

**Comment by Simann** [comment] 2020-03-07 18:24
Ty

**Comment by Simann** [comment] 2020-03-10 16:48
Umm bump?

**Comment by S-B99** [comment] 2020-03-10 20:11
Look at the number of opened issues, and look at the date you last commented.

**Comment by Simann** [comment] 2020-03-10 21:28
Ok I looked and?

**Comment by S-B99** [comment] 2020-03-10 21:33
To quote my response to someone earlier, 
> can you please rub your collective 3 brain cells

and draw the conclusion that 'bumping' does literally nothing on github other then send people a notification, and if you look at the amount of opened issues you'll realize that sending a bunch of people a notification will not make it happen faster or earlier.

**Comment by MightyKnight** [comment] 2020-03-19 17:49
@Simann Your issue seems to be almost a duplicate of #848.
Please add **additional information** (options etc.) there as a **comment**, so we can keep track of it in one place.

**Closed by MightyKnight** 2020-03-19 17:49 UTC
Labels: Suggestion

**Comment by Simann** [comment] 2020-03-19 17:52
:( its 2018

**Comment by S-B99** [comment] 2020-03-19 17:54
and? you could say that about the other 700 opened issues. it's still a duplicate
