### ISSUE TITLE
Enderpearl Rescue

### ISSUE THREAD

**Issue by fluse1367** [ImpactDevelopment/ImpactIssues#2276] opened 2020-05-12 16:52 UTC
**Is your feature request related to a problem? Please describe.**
Serverlag or other things can sometimes cause you fall into the void, lava or other dangerous terrain that you wouldn't be really able to survive on your own (unless ur a god), especially in such a stressful situation where you have the literal minecraft death in front of your eyes.

**Describe the solution you'd like**
If you have enderpearls in the hotbar (or even in the inventory) "Enderperal Rescue" would search for a safe spot (preferably the safest one) and throw a enderpearl for you. If it cannot find a safe spot on its own, maybe its possible that it'll pearl you onto a wall and build a block beneath you. Anything better than death.

**Describe alternatives you've considered**
Throw the pearl on your own. Very difficult considering this stressful situation.

**Additional context**
Maybe also another kind of "NoFall" in case you dont have a water bucket with you (and NoFall on packet isnt working on the server). I wouldn't say that this should be another mode of NoFall, since NoFall cancels all of the fall damage, whereas "Enderperal Rescue" does still some damage. But again, anything better than death.

**Comment by MightyKnight** [comment] 2020-05-12 19:14
Duplicate of #1359

**Closed by MightyKnight** 2020-05-12 19:14 UTC
Labels: Suggestion
