### ISSUE TITLE
suggestion: bed aura.

### ISSUE THREAD

**Issue by not-moooomoooo** [ImpactDevelopment/ImpactIssues#2235] opened 2020-05-03 07:07 UTC
There is a feature called crystal aura already in the client, and this would be similar. Whenever a bed is placed, impact will automatically sleep/right click on it! This would be very useful for pvp (bedbombing in the nether).

**Comment by dominikaaaa** [comment] 2020-05-03 18:04
Duplicate of #216

**Closed by dominikaaaa** 2020-05-03 18:04 UTC
Labels: Suggestion
