### ISSUE TITLE
Sneak on edge of a block

### ISSUE THREAD

**Issue by destinythedev** [ImpactDevelopment/ImpactIssues#2161] opened 2020-04-10 09:01 UTC
It would be awesome if there is feature that could automatically sneak when the player reaches an edge of a block, almost like a more legit version of Safe Walk. This could be useful if the player wanted to speed bridge legit.

**Comment by zanaphrax** [comment] 2020-04-28 21:04
this could be an option for safewalk.

**Comment by dominikaaaa** [comment] 2020-04-28 22:41
Duplicate of #898

**Closed by dominikaaaa** 2020-04-28 22:41 UTC
Labels: Suggestion
