### ISSUE TITLE
Chest Stealer Suggestions

### ISSUE THREAD

**Issue by Raulsack69** [ImpactDevelopment/ImpactIssues#1715] opened 2019-10-08 05:23 UTC
The "Steal" tab only exists for chests, when it would be nice if it would appear in shulker boxes as well. 

It would also be nice if there was a "Deposit" tab next to the player's inventory, allowing them to dump their items into a chest with the same delay settings used for "stealing".

Lastly, when "Auto Close" is selected, it only closes the chest when the chest contents are completely empty when it should also close the chest automatically when the player's inventory is full.

**Comment by MightyKnight** [comment] 2020-03-29 01:17
We do not track multiple different suggestions in a single issue.
First one is a duplicate of #877 too.

**Closed by MightyKnight** 2020-03-29 01:17 UTC
Labels: Suggestion
