### ISSUE TITLE
1.15.2 Flight Antikick Doesn't Work

### ISSUE THREAD

**Issue by kyrieleis1889** [ImpactDevelopment/ImpactIssues#2223] opened 2020-04-28 20:44 UTC
When turning on Antikick for Vanilla or 3D mode, it will still kick me for flying.

**To Reproduce**
1. Go to Flight
2. Click on Mode
3. Scroll down to 3D
4. Fly continuously for 10+ seconds
5. Get kicked

**Expected behavior**
![image](https://user-images.githubusercontent.com/64475546/80535893-7ffec680-896f-11ea-86ef-4fba1ad03495.png)

- Impact Version: 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: AntiHunger (Effective), AutoCheat (Unknown), Middle Click Friend, AutoReconnect, Criticals (Packet), No Fall (Packet), Fast Interact, Log Position, NewChunks, StorageESP, Trajectories, AntiDesync, ESP (Shader), Nametags, Inventory, Search (0), No Push, No Slow, Tracers, Portals, Light
- Operating System: Windows 10

</details>

**Additional context**
Playing on a 1.15.2 Spigot Server with Factions plugins

**Comment by dominikaaaa** [comment] 2020-04-28 22:37
Duplicate of #1604

**Closed by dominikaaaa** 2020-04-28 22:37 UTC
Labels: Bug
