### ISSUE TITLE
Live trajectories

### ISSUE THREAD

**Issue by theheartbenvn** [ImpactDevelopment/ImpactIssues#1353] opened 2019-07-14 05:26 UTC
Can you please add live trajectories, which show the path of active flying Ender Pearl / Arrow / Snowball / Fire Charge in the world?

For example : If anyone shoots an projectile, there will be a line which draws from that projectile to the finish marker, just like the one that Huzuni has.

**Comment by ScanmanTM** [comment] 2019-07-14 10:20
![image](https://user-images.githubusercontent.com/46611235/61182293-0ccad480-a629-11e9-8444-fbc443e5a092.png)
![Webp net-resizeimage](https://user-images.githubusercontent.com/46611235/61182329-4ef41600-a629-11e9-824b-dd384fda40c5.jpg)

**Comment by ZeroMemes** [comment] 2019-07-16 16:01
Trajectories at the moment will just show the path if you throw the projectile, this suggestion is about showing the path of already travelling projectiles.

**Comment by theheartbenvn** [comment] 2019-07-16 16:35
> Trajectories at the moment will just show the path if you throw the projectile, this suggestion is about showing the path of already travelling projectiles.

Yes that's what i meant, thank you. Geez people nowadays can't read...

**Comment by theheartbenvn** [comment] 2019-07-16 16:36
![image](https://user-images.githubusercontent.com/16258774/61312393-8a0d6980-a822-11e9-97de-553f6852a215.png)
![image](https://user-images.githubusercontent.com/16258774/61312402-8da0f080-a822-11e9-9e41-d277ecb01180.png)

**Comment by theheartbenvn** [comment] 2019-07-16 16:38
![image](https://user-images.githubusercontent.com/16258774/61312500-baed9e80-a822-11e9-9528-0b72aa0f949e.png)

![image](https://user-images.githubusercontent.com/16258774/61312540-d062c880-a822-11e9-910c-5e34d267041d.png)

**Comment by theheartbenvn** [comment] 2019-07-16 16:39
> Trajectories at the moment will just show the path if you throw the projectile, this suggestion is about showing the path of already travelling projectiles.

Yes, this is what i meant. Thank you.

**Comment by Rindula** [comment] 2019-07-19 02:50
It's like an early alert to arrows or enderpearls with included target location to evade or invade 😄 hard to do but nice to have 😜

**Comment by thegamerx1** [comment] 2019-08-13 03:23
This could add a arrow avoiding module which would be pretty cool

**Comment by S-B99** [comment] 2020-02-26 14:09
Duplicate of #830

**Closed** 2020-02-26 14:09 UTC
Labels: Suggestion
