### ISSUE TITLE
KILLAURA not attaks players with 0 HP

### ISSUE THREAD

**Issue by DARKESTSOULER** [ImpactDevelopment/ImpactIssues#1451] opened 2019-07-25 16:02 UTC
On GommeHD and some other Servers especialy in GunGame the players got 0 HP on Nametags and the Aura not attaks them :c

**Comment by zPeanut** [comment] 2019-07-28 10:47
tried changing aura settings?

**Comment by MightyKnight** [comment] 2020-03-24 20:34
Duplicate of #1156

**Closed by MightyKnight** 2020-03-24 20:34 UTC
Labels: Awaiting response, Bug
