### ISSUE TITLE
Ability to add block states to nuker

### ISSUE THREAD

**Issue by Socialblade-zz** [ImpactDevelopment/ImpactIssues#2701] opened 2020-11-08 01:34 UTC
As far as i know, there is no way to define block states when adding blocks to the nuker list.

**Comment by CesiumCs** [comment] 2020-11-08 01:52
duplicate of #709?

**Comment by l1ving** [comment] 2020-11-08 02:10
Yes, If #709 were to be closed it would apply to similar modules

**Closed by l1ving** 2020-11-08 02:10 UTC
Labels: Suggestion
