### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by Heayth** [ImpactDevelopment/ImpactIssues#2286] opened 2020-05-15 04:01 UTC
**Describe the bug**
The game crashes once i open it.

**To Reproduce**
1. Launch vanilla Minecraft launcher
2. Launch impact 1.15.2
3. Impact will not respond then crash.
**Expected behavior**
The game to launch with no issues.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://pastebin.com/B58bxFFU
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  1.15.2
- Using Optifine?  no
- Using LiteLoader?  yes
- Enabled mods:  Killaura, elytra plus (not sure of speed) esp
- Operating System:  windows 10

</details>

**Additional context**

**Comment by hYdos** [comment] 2020-05-15 07:40
duplicate of #2285 you should close this one and head there instead

**Comment by ScanmanTM** [comment] 2020-05-15 09:55
How's it a dupe retard, different crash logs. 
Fix: you are not launching with the account that is linked in your dashboard.

**Closed by ScanmanTM** 2020-05-15 09:55 UTC
Labels: Bug

**Comment by JMar2006** [comment] 2020-05-21 17:44
I'm having this problem can anyone help

**Comment by JMar2006** [comment] 2020-05-21 17:50
How do I fix

**Comment by dominikaaaa** [comment] 2020-05-21 18:00
![maim-2020-05-21-14-00-12](https://user-images.githubusercontent.com/17222512/82590258-66fec500-9b6b-11ea-93e7-f702d54835aa.png)
