### ISSUE TITLE
Auto Weapon

### ISSUE THREAD

**Issue by Hot-Smelly-Garbage** [ImpactDevelopment/ImpactIssues#2087] opened 2020-03-24 18:36 UTC
**Describe the bug**
With auto weapon on, it switches out the sword with whatever you currently have in your hand.

**To Reproduce**
1. Go to Combat
2. Click on Auto Weapon
3. Attack

**Expected behavior**
It would switch to the sword and work.

**Screenshots**
No screenshot, but video!
https://streamable.com/1ihqo

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 20200323-1.15.2 Nightly
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: In video
- Operating System: Windows 64-Bit

</details>

**Additional context**

**Comment by MightyKnight** [comment] 2020-03-24 19:01
Duplicate of #1033

**Closed by MightyKnight** 2020-03-24 19:01 UTC
Labels: Bug
