### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by phillipsawyer** [ImpactDevelopment/ImpactIssues#2081] opened 2020-03-22 23:43 UTC
Auto mining & auto farming is really jittery and not smooth and it's pretty obvious when someone is using it. SmoothAim is brilliant, however there is no equivalent for auto mining / farming

It would be extremely useful to have smooth farming / mining, or simply a mod that makes all aiming smooth instead of jittery.

This may be tricky to implement since auto farm uses baritone but hopefully it's worth considering!

**Comment by S-B99** [comment] 2020-03-22 23:45
Duplicate of #1992

**Closed by S-B99** 2020-03-22 23:45 UTC
Labels: Suggestion

**Comment by phillipsawyer** [comment] 2020-03-22 23:52
I don't think it's a duplicate because he talks about smoothaiming not working while baritone is pathfinding, however mine is about smoothly aiming at the farmed blocks

**Comment by S-B99** [comment] 2020-03-22 23:53
It's the same code to do that stuff, baritone wise.
