### ISSUE TITLE
Random tracers on cracked servers.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactIssues#1032] opened 2019-03-25 13:08 UTC
### What happens?
Random tracer(s) show up whenever a player joins a server (usually happens on cracked servers for some reason) and point in a direction you can't look at. It's weird and impossible to look in their direction. It's like they're always to the side.
https://youtu.be/LbxJlnYfFhQ

### Exact steps to reproduce?
-Turn tracers on (cracked servers should always work).
-Let a player join that's outside of your render distance.

### Yeesss.
- Impact Version: Was a thing back in 4.4 and still is in 4.6
- Using Optifine? Yes.
- Using LiteLoader? No.
- Enabled mods: Tracers.

**Comment by Nikita11790** [comment] 2019-03-27 03:35
Could this be anti-cheat?

**Comment by MastaNub** [comment] 2019-03-27 17:18
Highly doubt.

**Comment by dominikaaaa** [comment] 2020-09-22 00:38
Sounds like a duplicate of the antibots false positive bug.

**Closed by dominikaaaa** 2020-09-22 00:38 UTC
Labels: Bug, GUI
