### ISSUE TITLE
Custom Modules

### ISSUE THREAD

**Issue by EdgyBoi2414** [ImpactDevelopment/ImpactIssues#2243] opened 2020-05-04 15:37 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be cool to be able to develop your own modules for the client. I'd see it working like a bukkit plugin would, It would open up a lot of new options for adding specific hacks for specific servers.

**Describe alternatives you've considered**
I tried developing my own client but Jesus christ events have got my brain frazzled.

**Additional context**
N/A

**Comment by dominikaaaa** [comment] 2020-05-04 15:39
Duplicate of #911

**Closed by dominikaaaa** 2020-05-04 15:39 UTC
Labels: Suggestion
