### ISSUE TITLE
Cheststealer missing shulkerbox steal button

### ISSUE THREAD

**Issue by ThaUnknown** [ImpactDevelopment/ImpactIssues#2101] opened 2020-03-29 00:30 UTC
**Describe the bug**
Shulkerbox GUI is missing Steal button

**To Reproduce**
1. Open Shulkerbox
2. Realise steal button is missing

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: Impact nightly 20200309 for 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: -
- Operating System: Windows

</details>

**Comment by MightyKnight** [comment] 2020-03-29 01:15
Duplicate of #877

**Closed by MightyKnight** 2020-03-29 01:15 UTC
Labels: Bug
