### ISSUE TITLE
Impact - Riding hack doesn't affect speed on pig, but it affects speed on horse

### ISSUE THREAD

**Issue by SweHun** [ImpactDevelopment/ImpactIssues#1149] opened 2019-04-19 13:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by usereewrjrjeejr** [comment] 2019-04-19 19:07
Thanks for all the info will be fixed soon!!!

**Comment by dominikaaaa** [comment] 2020-09-22 00:24
Closed as can't reproduce. Reopen if you can still reproduce this.

**Closed by dominikaaaa** 2020-09-22 00:24 UTC
Labels: Awaiting response, Bug
