### ISSUE TITLE
Be able to move things in HUD

### ISSUE THREAD

**Issue by lSherozl** [ImpactDevelopment/ImpactIssues#2324] opened 2020-05-22 10:24 UTC
Impact is a great mod, but many people don't just play on Vanilla Minecraft, they play on other mods like RLCRAFT for example, so it becomes a problem when you are trying to add say the armor option and it's overlaying with the other things in the mod, same with the coordinates, or where the information shows up on your screen for what hacks your using currently. Here is a picture to display what I mean, armour interferes with water meter: 
![image](https://user-images.githubusercontent.com/65663746/82658224-df08d180-9be3-11ea-9404-d175007f7d1f.png)
Things in HUD should be moveable to where you want them, including the hack display which shows up always on the top right of the screen.
![image](https://user-images.githubusercontent.com/65663746/82658348-10819d00-9be4-11ea-93e2-0deaffd79a30.png)

**Comment by MightyKnight** [comment] 2020-05-28 16:22
Duplicate of #1471

**Closed by MightyKnight** 2020-05-28 16:22 UTC
Labels: Suggestion
