### ISSUE TITLE
Autosoup

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#2010] opened 2020-02-22 17:49 UTC
**Is your feature request related to a problem? Please describe.**
The soup module isnt automatic and is useless and when using kilaura it doesnt work
you have to bind it to a key and spam that key

**Describe the solution you'd like**
make it automatic and make it work with killaura

**Describe alternatives you've considered**
change client which i will probably do

**Additional context**

**Comment by S-B99** [comment] 2020-02-22 17:51
Duplicate of #1424

**Comment by EmeraldSnorlax** [comment] 2020-02-22 17:52
![image](https://user-images.githubusercontent.com/43452521/75096891-ffe96880-559b-11ea-9c03-6fe001c4575c.png)
yes, because soup *clearly* isnt automatic.

**Comment by S-B99** [comment] 2020-02-22 17:52
mfw

**Closed by S-B99** 2020-02-22 17:51 UTC
Labels: Suggestion
