### ISSUE TITLE
Auto eat bugged while tunneling

### ISSUE THREAD

**Issue by Laurens54321** [ImpactDevelopment/ImpactIssues#1903] opened 2019-12-12 00:24 UTC
When using baritone and auto eat it bugges out and it gets stuck with food in your hand. This can be fixed by holding in right mouse button to eat it manually.

**Comment by koutsie** [comment] 2019-12-24 00:12
> autoeat exists as a mod.

**Comment by S-B99** [comment] 2020-02-17 23:47
Duplicate of #1902

**Closed by S-B99** 2020-02-17 23:47 UTC
Labels: Bug
