### ISSUE TITLE
Exiting F3 Menu Crashes Client

### ISSUE THREAD

**Issue by parker-stephens** [ImpactDevelopment/ImpactIssues#2198] opened 2020-04-22 00:02 UTC
Using the latest nightly, 04-21, along with the latest Optifine build for 1.15.2. Exiting the F3 menu crashes the game. Tested on 1.15.2, no issues, 1.15.2 w/Optifine, no issues, 1.15.2 Impact Nightly, no issues. Only occurs with Impact w/Optifine.
[crash-2020-04-21_18.48.02-client.txt](https://github.com/ImpactDevelopment/ImpactIssues/files/4513085/crash-2020-04-21_18.48.02-client.txt)

**Comment by LeafHacker** [comment] 2020-04-22 00:42
This is caused by `fps = Integer.parseInt(mc.debug.split(" ")[0])` in `render.hud.WidgetInfo`. For some reason `mc.debug.split(" ")[0]` is `"34/7"` according to the crash-report.

Enabling "Nicer FPS" will work around this issue until a fix is released.

**Comment by LeafHacker** [comment] 2020-04-22 00:48
Looks like OptiFine adds additional info to the debug screen; vanilla only shows the average FPS while OptiFine also shows the minimum FPS.

OptiFine: 
![image](https://user-images.githubusercontent.com/23565638/79928451-eac57480-843a-11ea-8a35-7ecc94049508.png)

Vanilla: 
![image](https://user-images.githubusercontent.com/23565638/79928541-1ea09a00-843b-11ea-9aee-7fea1c2b4552.png)

**Comment by LeafHacker** [comment] 2020-04-22 01:06
Fixed in the next nightly

**Closed by LeafHacker** 2020-04-22 01:06 UTC
Labels: Bug, Crash, Optifine
