### ISSUE TITLE
Hypixel Murder Out of date

### ISSUE THREAD

**Issue by Hobblebobble-byte** [ImpactDevelopment/ImpactIssues#2311] opened 2020-05-20 09:38 UTC
**Describe the bug**
Hypixel seems to have introduced the murderer using different items, Like Roses, Diamond weapons, Axes, or others, making the murderer detection not work properly

**To Reproduce**
1. Play Hypixel Murder with Misc>Murder (mode set to Hypixel)
2. Play until a player uses a non-standard murder weapon
3. The player will not highlight as a murderer, and could infact light up blue if a bow is acquired through other means

**Expected behavior**
A player should highlight red once they hold out applicable murderer weapons

- Impact Version: Nightly 20200512 - 1.15.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Autocheat, Trajectories, Nametags, Murder
- Operating System: Win10 64

**Comment by dominikaaaa** [comment] 2020-05-20 12:56
See #1990 and #1894

Dupe of #2256 as well

**Closed by dominikaaaa** 2020-05-20 12:56 UTC
Labels: Bug
