### ISSUE TITLE
There is no "Steal" button when opening Shulker Boxes

### ISSUE THREAD

**Issue by SpikeVN** [ImpactDevelopment/ImpactIssues#2881] opened 2021-02-03 03:21 UTC
_I don't know this is a bug or a feature lack. I'll just report it._

**Solutions**
I'm new, so I'll just follow the template.
Add it in Shulker Box opening UI, like chests and ender chests.

**Comment by berrely** [comment] 2021-02-03 19:12
Duplicate of #877

**Closed by berrely** 2021-02-03 19:12 UTC
Labels: Suggestion
