### ISSUE TITLE
Automatically eat soup whenever health is low

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactIssues#2007] opened 2020-02-22 11:55 UTC
Cant join discord server so.

wheres the autosoup? do i have to bind the soup and be fucking pressing the key every second

also the soup doesnt work while using killaura which sucks

**Comment by S-B99** [comment] 2020-02-22 14:43
There is no auto soup. Why would you ever need to eat soup on an anarchy server. You can use auto eat.

**Comment by thegamerx1** [comment] 2020-02-22 16:42
i mean autosoup for kit pvp with soups not for hunger

**Comment by S-B99** [comment] 2020-02-22 17:10
the fuck kind of anarchy server has kit pvp enabled

**Comment by thegamerx1** [comment] 2020-02-22 17:12
what kind of anarchy server needs smooth aim and more modules like that? they could just use the less legit kill aura..

**Comment by Toton7896** [comment] 2020-02-22 17:12
but remember that impact isn't 'anarchy only' client. it is good that it has many features

**Comment by S-B99** [comment] 2020-02-22 17:13
mfw people ask for modules for kit pvp
petition to lock this thread

**Comment by S-B99** [comment] 2020-02-22 17:13
impact is not for your 1.8 whatever minigame server.

**Comment by thegamerx1** [comment] 2020-02-22 17:14
if it is for only anarchy servers remove the soup and pot modules they are useless if they arent automatic

**Comment by S-B99** [comment] 2020-02-22 17:15
![Screenshot_20200222_121538](https://user-images.githubusercontent.com/17222512/75096380-0b716b00-556d-11ea-9e54-3743416d22b9.png)

why was this issue created

**Comment by thegamerx1** [comment] 2020-02-22 17:16
because you have to press the key to recover hp it isnt automatic its useless

**Comment by S-B99** [comment] 2020-02-22 17:18
It isn't supposed to be automatic? It'

**Comment by thegamerx1** [comment] 2020-02-22 17:18
why would you want it to be manual?

**Comment by S-B99** [comment] 2020-02-22 17:20
Because Auto isn't in the name.

You press a keybind. That's it. Is it so hard to press something on your keyboard.

**Comment by thegamerx1** [comment] 2020-02-22 17:21
yes because when you are on servers full of hackers you will lose hp quickly and pressing the key continously to dont die isnt very fun also it doesnt work while killauraing

**Comment by S-B99** [comment] 2020-02-22 17:22
Again, why are you using soups to heal. Use a god apple

**Comment by thegamerx1** [comment] 2020-02-22 17:22
because its a kit pvp not god apples

**Comment by S-B99** [comment] 2020-02-22 17:23
That's your fault for playing kit pvp

**Comment by thegamerx1** [comment] 2020-02-22 17:24
wow okay going to change client i see this is going nowhere

**Comment by S-B99** [comment] 2020-02-22 17:25
What kind of a person uses an anarchy oriented utility mod for kit pvp

**Comment by thegamerx1** [comment] 2020-02-22 17:26
what kind of person adds a useless module to a anarchy oriented hack

**Comment by S-B99** [comment] 2020-02-22 17:27
Which hack lol. Not my fault that you're using some useless module in some hack.

**Comment by thegamerx1** [comment] 2020-02-22 17:34
if it is ONLY for anarchy servers why does it have minigame modules lel

**Comment by S-B99** [comment] 2020-02-22 17:34
Such as?

**Comment by thegamerx1** [comment] 2020-02-22 17:35
![image](https://user-images.githubusercontent.com/34986564/75096668-172b5480-55a2-11ea-96b1-e10ae7ed206b.png)

**Comment by S-B99** [comment] 2020-02-22 17:35
:woman_shrugging:

**Comment by S-B99** [comment] 2020-02-22 17:36
I didn't say it was only for anarchy servers, you did. I only asked why you would need soup when you can use god apples lol.

**Comment by thegamerx1** [comment] 2020-02-22 17:36
`the fuck kind of anarchy server has kit pvp enabled` arent u saying it here?

**Comment by S-B99** [comment] 2020-02-22 17:38
I asked what kind of anarchy server has kit pvp.

**Comment by thegamerx1** [comment] 2020-02-22 17:38
arent you saying there that it is only for anarchy servers?

**Comment by S-B99** [comment] 2020-02-22 17:40
Uh, no.

> I didn't say it was only for anarchy servers, you did. I only asked why you would need soup when you can use god apples lol.

**Comment by thegamerx1** [comment] 2020-02-22 17:43
i repeat no god apples on kit pvp

**Comment by S-B99** [comment] 2020-02-22 17:44
Then eat whatever else you can eat lol

**Comment by thegamerx1** [comment] 2020-02-22 17:44
do u even know what soup pvp is?

**Comment by S-B99** [comment] 2020-02-22 17:45
I don't and I couldn't care less. It's not my fault you don't have god apples and are choosing to eat soup for some reaso.

**Comment by thegamerx1** [comment] 2020-02-22 17:45
BECAUSE I CANT GET GOD APPLES ON KIT PVP OMG

**Comment by S-B99** [comment] 2020-02-22 17:46
I mean that's not my fault really.

**Comment by S-B99** [comment] 2020-02-22 17:46
You chose to play kit pvp, not me.

**Comment by thegamerx1** [comment] 2020-02-22 17:46
then why dont add automatic option to soup module?

**Comment by S-B99** [comment] 2020-02-22 17:47
Because you can just eat the soup lol

**Comment by S-B99** [comment] 2020-02-22 17:47
This issue was a question. It's labelled question. You asked if there was autosoup and the answer is no.

**Comment by S-B99** [comment] 2020-02-22 20:53
This is a duplicate of #1424 then, no?

**Comment by LeafHacker** [comment] 2020-02-22 21:00
yes

**Closed by LeafHacker** 2020-02-22 21:00 UTC
Labels: Suggestion

**Comment by S-B99** [comment] 2020-02-22 21:02
I also marked #2010 as a duplicated because the kid asked twice
