### ISSUE TITLE
Regex chat filter

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactIssues#2231] opened 2020-05-01 15:11 UTC
Players using PhiBot, mooomooo, etc flood the chat with garbage. Mass /ignoring everyone is a pain.

**Describe the solution you'd like**
A way to regex filter out messages similar to [here](https://www.reddit.com/r/constantiam/comments/gak2vr/how_to_filter_out_annoying_bot_commands_without/)

**Comment by dominikaaaa** [comment] 2020-05-01 20:43
Duplicate of #1707

**Closed by dominikaaaa** 2020-05-01 20:43 UTC
Labels: Suggestion
