### ISSUE TITLE
Alt manager alignment issues on release build

### ISSUE THREAD

**Issue by dumbasPL** [ImpactDevelopment/ImpactIssues#577] opened 2018-04-30 18:49 UTC
Alt text is positioned incorrectly on 4.2

![image](https://user-images.githubusercontent.com/29180158/39444088-c9bc0776-4cb6-11e8-9432-8179df09aece.png)

### Game output?

<details> 
  <summary>Game output</summary>

```
20:38:07 | launcher | Preparing to launch minecraft client for 1.12.2-Impact_4.2
-- | -- | --
20:38:07 | launcher | Couldn't get hash for org/spongepowered/mixin/0.7.7-SNAPSHOT/mixin-0.7.7-SNAPSHOT.jar from http://dl.liteloader.com/versions/org/spongepowered/mixin/0.7.7-SNAPSHOT/mixin-0.7.7-SNAPSHOT.jar.sha1: HTTP 404: Not Found
20:38:07 | launcher | Have local file C:/Users\Mariusz\AppData\Roaming\.minecraft\libraries\org/spongepowered/mixin/0.7.7-SNAPSHOT/mixin-0.7.7-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
20:38:07 | launcher | Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
20:38:07 | launcher | Have local file C:/Users\Mariusz\AppData\Roaming\.minecraft\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
20:38:08 | launcher | Checking installations.
20:38:08 | launcher | Minecraft client 1.12.2-Impact_4.2 is ready to start.
20:38:08 | launcher | Starting!
20:38:08 | launcher | Using default game log configuration client-1.12.xml (outputs XML)
20:38:10 | LaunchWrapper | Loading tweak class name clientapi.load.ClientTweaker
20:38:10 | LaunchWrapper | Using primary tweak class name clientapi.load.ClientTweaker
20:38:10 | LaunchWrapper | Calling tweak class clientapi.load.ClientTweaker
20:38:10 | ClientAPI | Injecting into ClassLoader
20:38:10 | mixin | SpongePowered MIXIN Subsystem Version=0.7.7 Source=file:/C:/Users/Mariusz/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.7-SNAPSHOT/mixin-0.7.7-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
20:38:11 | mixin | FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
20:38:11 | ClientAPI | Initialized Mixin bootstrap
20:38:11 | mixin | Compatibility level set to JAVA_8
20:38:11 | mixin | Mixin config mixins.capi.json does not specify "minVersion" property
20:38:11 | ClientAPI | Loaded ClientAPI mixin configuration
20:38:11 | mixin | Mixin config mixins.client.json does not specify "minVersion" property
20:38:11 | ClientAPI | Loaded Client mixin configuration
20:38:11 | LaunchWrapper | Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
20:38:11 | LaunchWrapper | Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
20:38:14 | LaunchWrapper | Launching wrapped minecraft {net.minecraft.client.main.Main}
20:38:17 | bib | Setting user: dumbasPL
20:38:24 | bib | LWJGL Version: 2.9.4
20:38:25 | cev | Reloading ResourceManager: Default
20:38:26 | chm | Starting up SoundSystem...
20:38:26 | chm | Initializing LWJGL OpenAL
20:38:26 | chm | (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
20:38:27 | chm | OpenAL initialized.
20:38:27 | chm | Sound engine started
20:38:36 | cdp | Created: 1024x512 textures-atlas
20:38:41 | com.mojang.text2speech.NarratorWindows | Narrator library for x64 successfully loaded
20:38:44 | Impact | Loading Fonts
20:38:45 | Impact | Checking for Updates
20:38:45 | Impact | Loading Users
20:38:47 | Impact | Initialized 106 mods!
20:38:48 | bjb | [CHAT] [Impact] Added Graf as a friend!
20:38:49 | bib | ########## GL ERROR ##########
20:38:49 | bib | @ Pre render
20:38:49 | bib | 1282: Invalid operation

```
</details>

### Additional Client Info

- Impact Version: 4.4 for 1.12.2
- Using Optifine? Doesn't matter
- Enabled mods: None
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment] 2018-04-30 18:54
What is your GUI scale setting (under video options) and what resolution/aspect ration is the game window?

**Comment by Pabsb** [comment] 2018-04-30 22:48
Don't post repeat issues as I already opened one up a while ago.

**Comment by LeafHacker** [comment] 2018-04-30 23:38
@Pabsb normally I would mark this as a duplicate, however since this issue is more specific I will close the original in favour of this one. As mentioned in my comment over on #560, please open separate issues for each bug. Thanks!

**Comment by LeafHacker** [comment] 2018-04-30 23:40
I still can't reproduce this after playing around with different scales and aspect ratios. What GPUs are you guys running? And what resolution is the game window at?

**Comment by Pabsb** [comment] 2018-04-30 23:55
The hell you mean his is more specific lol? I put way more info in mine and he just has 2 lines.....

**Comment by LeafHacker** [comment] 2018-05-01 00:54
Specific as in narrower scope. Less topics covered. Confined to a single bug instead of four. Also even the generic title of "visual glitch" is more descriptive than simply "Bug 1" or "Bugs"

I was really struggling to reproduce this in 4.3... but was able to instantly in the 4.2 release. The odd thing is that the GUI hasn't been changed, so this must be caused by the obfuscation or something... @ZeroMemes ??

**Comment by MightyKnight** [comment] 2019-01-05 12:43
Is this still an issue in 4.4?

**Comment by ZeroMemes** [comment] 2020-03-29 23:45
Can't reproduce and this issue is *very* old. Closing, if the issue is still present open a new issue demonstrating it on the latest version.

**Closed by ZeroMemes** 2020-03-29 23:45 UTC
Labels: Bug, GUI

**Comment by LeafHacker** [comment] 2020-03-30 00:51
I vaguely remember fixing this
