### ISSUE TITLE
Passive 'Inventory Peeker' GUI Element Module

### ISSUE THREAD

**Issue by MarauderKnight3** [ImpactDevelopment/ImpactIssues#2194] opened 2020-04-20 21:14 UTC
**Is your feature request related to a problem? Please describe.**
No. This feature is just something quality-of-life, I had the thought that if I were in combat I might want to see all the supplies I had in real-time, but it's not necessary per se.

**Describe the solution you'd like**
A inventory peeker module like seen on other clients that, while outside of other menus, shows you the twenty-seven inventory slots your player has in a repositionable and (possibly) resizeable GUI window.

**Describe alternatives you've considered**
A simpler resource viewer that allows you to see the amount of a relevant resource as a number below/above the cross hair, such as amount of remaining blocks throughout the inventory of the type one is holding, and amount of held arrows or tipped arrows available while holding a bow, and/or durability as it is shown in the item's tooltip (like 34/65).
 
**Additional context**
As seen in this [video on youtube](https://www.youtube.com/watch?v=wFjZbtRsTjE&t)
I do not recommend cutting the GUI off as a feature but this shows exactly what I was talking about.
If possible, it would be wonderful if the Inventory Peeker window would reflect the current texture pack via cutting the background image from the inventory image file used by the texture pack.

**Comment by dominikaaaa** [comment] 2020-04-20 21:15
Duplicate of #2003

**Closed by dominikaaaa** 2020-04-20 21:15 UTC
Labels: Suggestion
