### ISSUE TITLE
Keep x amount of items for AutoEject

### ISSUE THREAD

**Issue by turret001** [ImpactDevelopment/ImpactIssues#2208] opened 2020-04-24 17:26 UTC
**Is your question request related to a problem? Please describe.**
No, this is a suggestion

**Describe what you are trying to achieve**
It would be nice to add a "keep x amount of items in inventory" option for autoeject. This could be useful for Baritone auto miner. 

**Additional context**
Nope

**Comment by turret001** [comment] 2020-04-24 17:27
I'm sorry, I accidentally made this a question instead of suggestion. I'm not good with github

**Comment by MightyKnight** [comment] 2020-05-28 17:15
Duplicate of #1669

**Closed by MightyKnight** 2020-05-28 17:15 UTC
Labels: Suggestion
