### ISSUE TITLE
Elytra+ doesn't keep same y it slowly goes down

### ISSUE THREAD

**Issue by ElectroYModz** [ImpactDevelopment/ImpactIssues#2384] opened 2020-06-08 22:47 UTC
When you use Elytra+ you don,t keep the same y level you slowly fall down

keep the same y level while you don't press anything

**Comment by dominikaaaa** [comment] 2020-06-09 01:51
duplicate of some issue. try searching next time

**Closed by dominikaaaa** 2020-06-09 01:51 UTC
Labels: Bug
