### ISSUE TITLE
Is Impact Client Died?

### ISSUE THREAD

**Issue by yodaluca23** [ImpactDevelopment/ImpactIssues#3432] opened 2022-08-10 17:43 UTC
Their hasn't been an update for over a year, the latest version it supports is 1.16 and the issue count is almost at 1k can someone confirm for me wether or not impact is died? I really hope not because it is amazing, it's open source, free, and I love it and use it a lot.

**Comment by feliscatusmeows** [comment] 2022-08-25 03:15
> it's open source
Wait where's the source code?

**Comment by PandaUprising** [comment] 2022-09-06 04:49
Duplicate of #3429

**Comment by CesiumCs** [comment] 2022-10-24 21:40
> > it's open source
> > Wait where's the source code?

nah hes just misinformed - impact has a github, but the source code isnt in any repo. 

>  can someone confirm for me wether or not impact is died? 

its not even confirmed for any of us, we just assume that since the discord was taken down there just isnt any motivation

**Closed by CesiumCs** 2022-10-24 21:40 UTC
Labels: Question
