### ISSUE TITLE
Add an "Enemies" or "Rivals" category for players.

### ISSUE THREAD

**Issue by Raulsack** [ImpactDevelopment/ImpactIssues#1640] opened 2019-09-10 23:07 UTC
**Is your feature request related to a problem? Please describe.**
Currently you can categorize players as "Friends" or leave them as non-friends (default). Each have their own tracer/color options. It would be nice to be able to add players to a "Enemies" or "Rival" category with its own color and tracer options (like Red) for people who are on your bad side.

**Describe the solution you'd like**
Add a "Enemies" or "Rivals" category for players with their own tracer/color options separate from Friends and Non-Friends.

**Describe alternatives you've considered**
Memorizing every player name who has ever wronged me.

**Additional context**
None.

**Comment by Raulsack69** [comment] 2019-10-09 03:06
Duplicate of [#515](https://github.com/ImpactDevelopment/ImpactIssues/issues/515)

I lost access to my account and as such have lost the ability to close this issue myself. Somebody with more elevated privileges feel free to close this.

**Closed** 2019-10-09 05:16 UTC
Labels: Suggestion
