### ISSUE TITLE
[1.14] X-Ray not working with OptiFine installed

### ISSUE THREAD

**Issue by Thewest123** [ImpactDevelopment/ImpactIssues#1729] opened 2019-10-12 08:55 UTC
**Describe the bug**
As the title says, if I turn on x-ray, it just makes everything brighter, but I can't see through the ground. (Wireframe or Wireframe+Xray works tho if it helps)

**To Reproduce**
1. Install Minecraft 1.14.4
2. Install OptiFine HD F3 Ultra
3. Install Impact
4. Open world, turn on X-Ray

**Expected behavior**
Seeing selected blocks through the ground.

**Screenshots**
https://imgur.com/a/kcdVg3v

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.8.1 for 1.14.4
- Using Optifine? Yes - 14.4.4_HD_U_F3
- Enabled mods: Doesn't matter, if none, still doesn't work
- Operating System: Windows 10 64bit

</details>

**Comment by enderman2s** [comment] 2019-10-12 09:07
The devs already know about xray not working with optifine, sadly the only thing you can do is use it without optifine unless you 100% need it.

**Comment by leijurv** [comment] 2019-10-12 17:31
Sorry, optifine breaking our xray in 1.13 and 1.14 has been a known issue going back to march, this is a duplicate of dozens of other issues.

**Closed by leijurv** 2019-10-12 17:31 UTC
Labels: 1.14, Bug
