### ISSUE TITLE
Feature for Baritone.

### ISSUE THREAD

**Issue by gupah** [ImpactDevelopment/ImpactIssues#1443] opened 2019-07-25 10:17 UTC
A baritone option in creative mode, which automatically collects the blocks needed to build the schematics. In survival mode, show a list with the amount of materials needed (and put how many items are missing) or the bot, collect the necessary materials on its own.

**Comment by dominikaaaa** [comment] 2020-06-12 15:52
Duplicate of https://github.com/cabaletta/baritone/issues/1675

In the future, please make issues in the proper repository

**Closed by dominikaaaa** 2020-06-12 15:52 UTC
Labels: Suggestion
