### ISSUE TITLE
Please add HoleESP

### ISSUE THREAD

**Issue by SKRecreated** [ImpactDevelopment/ImpactIssues#2883] opened 2021-02-03 03:58 UTC
**Is your feature request related to a problem? Please describe.**
Im always mad when people in 2b2t are hunting me down and I have no idea where the nearest safe bedrock hole is. (Well maybe im not mad but it would be nice if I knew where to go.)

**Describe the solution you'd like**
I would like HoleESP added so I dont get mushed. 
**Describe alternatives you've considered**
Ive considered using sal but its not as good as impact. 
**Additional context**

**Comment by donteatapples** [comment] 2021-02-03 07:57
yes

**Comment by berrely** [comment] 2021-02-03 19:10
Duplicate of #2245

**Closed by berrely** 2021-02-03 19:10 UTC
Labels: Suggestion
