### ISSUE TITLE
autoeject and block variations (1.12.2)

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactIssues#1312] opened 2019-06-20 22:25 UTC
**Is your feature request related to a problem? Please describe.**
Autoeject is limited to items that aren't variations so for instance one can't add diorite or blue stained glass to autoeject without adding entire range of related blocks along with that

**Describe the solution you'd like**
expand `autoeject add` syntax to handle numeric item ids

**Describe alternatives you've considered**
n/a

**Additional context**
This was brought up once on this issue page in 2018 but I think everyone forgot about it and also it was referring to minecraft's damage system for blocks (I dont know what that is). Im proposing to use item ids so for example: `minecraft:sponge` is both wet and normal sponge - indistinguishable. Item id of sponge is 19, wet sponge is 19:1. So why not use that instead?

**Comment by Cerbiac** [comment] 2019-06-20 22:42
`minecraft:sponge:1`?

**Comment by a6d6061ed1** [comment] 2019-06-20 23:47
> `minecraft:sponge:1` should work.

I didnt test it with sponge but diorite doesnt work this way, it says that argument is invalid and item was expected

**Comment by usereewrjrjeejr** [comment] 2019-06-21 01:48
Damage values don't work ♿

**Comment by MightyKnight** [comment] 2020-03-24 20:07
Still a duplicate of #709

**Closed by MightyKnight** 2020-03-24 20:07 UTC
Labels: Suggestion
